name: Deploy SMMPanels.net Astro App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            whoami
            pwd

            node -v
            npm -v

            which node
            which npm

            echo "Building Astro..."
            curl http://128.140.35.62:4322/?Task=Full&token=${{ secrets.WEBHOOK_TOKEN}}

            echo "Deployment Started successfully!"
