name: Deploy to VPS

on:
  workflow_dispatch:    
  
  push:
    branches:
      - main # Change to 'master' if that is your primary branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            whoami
            pwd

            node -v
            npm -v

            which node
            which npm

            # 1. Navigate to your build project directory on the VPS
            cd var/www/hosted_projects/SMMPanels.net/live

            # 2. Pull the latest changes
            git pull origin main

            echo "Building Astro..."
            # 3. Execute your link / curl command
            curl --fail "http://128.140.35.62:4322/deploy?key=${{ secrets.WEBHOOK_TOKEN }}"

            echo "Webhook Called..."
